const boysNames = [
  "Abhijit Sahoo",
  "Abhishek Ratnakar",
  "Adarsh Jaiswal",
  "Akshat Baranwal",
  "Anurag Kumar",
  "Arpit Tripathi",
  "Aryan Singh",
  "Athar Ramzan",
  "Darshit Sengra",
  "Devesh Verma",
  "Gopi Kishan",
  "Himkar Singh",
  "Kalash Mishra",
  "Kasula Mahendra",
  "Kharuhang Rai",
  "Kushagra Pandey",
  "Jagdish Sunil Pednekar",
  "Manit Choudahary",
  "Muhammed Ayaan Taimur",
  "Nikhil Kumar",
  "Parmardeep Kumar",
  "Pravesh Arya",
  "Raj Aryan",
  "Raj Shekhar",
  "Ritesh Sharma",
  "Sachin Yadav",
  "Mattapalli Srinath Rao",
  "Soham Pal",
  "Soumyaditya Batabyal",
  "Vedant",
  "Aamir Belal Khan",
  "Abhishek Kumar Chauhan",
  "Aditya Pratap",
  "Agam Kundu",
  "Anurag Khubalkar",
  "Arpit Mishra",
  "Arjun Prakash Rana",
  "Aryan Burnwal",
  "Ashutoshmani Shukla",
  "Chaitanya",
  "Deepen",
  "Gautam Krishn Sharma",
  "Himanshu",
  "Karan Vishwajyoth",
  "Kumar Aditya",
  "Manish YM",
  "Mayank Sharma",
  "Narendra Patel",
  "Palakurthi Sai Bharadwaja",
  "Prakash Bhattacharya",
  "Priyanshu Kumar",
  "Ravish",
  "Saahi Dubey",
  "Sancheet Kumar",
  "Shivam Chaudhary",
  "Shrey Rathore",
  "Sofiyan Shaikh",
  "Tanishq Nitin Bhosale",
  "Shwetansh Singh",
  "Soni Jay Gaurang",
  "Vaibhav Kumawat",
  "Sanket Jadhav",
  "Aditya Kumar Sahoo",
  "Anshuman Ojha",
  "Anupam Singh",
  "Arpit Maurya",
  "Arya Sonwane",
  "Ashutosh Kumar Singh",
  "Avan",
  "Deepanshu Yadav",
  "Divyansh Gupta",
  "Priyanshu Pandey",
  "Harshit Gandhi",
  "Kallal Mukherjee",
  "Krishna Aggarwal",
  "Manish Kumar",
  "Masam Varshith Yadav",
  "Nagilla Aaradhya",
  "Om Sharma",
  "Pratyksh Gupta",
  "Priyanshu",
  "Rishab",
  "Rohit Kumar Modi",
  "Sahil",
  "Shiva MR",
  "Utkarsh Pandey",
  "Vishvendra Sangwa",
  "Yug Ramoliya",
  "Shubham Mishra",
  "Sonam",
  "Syed Abdur Rehman",
  "Zainul Abedeen",
  "Saurabh Singh",
  "Shashank Goel",
  "Abhijit Das",
  "Abhishek Suryavanshi",
  "Aditya",
  "Aditya Jagrani",
  "Anshman Singh",
  "Arnab Boro",
  "Arvind Kumar",
  "Aryansh Chandra",
  "Atharva Vinod Babhulgaonkar",
  "Debashish Giri",
  "Devesh Singh",
  "Hardik Tiwari",
  "Jay Sandeep Sawant",
  "Krishant Tanti",
  "Laksh Oswal",
  "Lakshya Yadav",
  "Manoj Chandrappa Lamani",
  "Muzaffar Hossain",
  "Nitish Sharma",
  "Pranjal Negi",
  "Praveen Kumar",
  "Prince Kumar Maurya",
  "Raunak Kumar",
  "Rituraj Bhattacharjee",
  "Rohan Saini",
  "Rudra Pratap Singh",
  "Shreedhar Agrawal",
  "Som Kumar",
  "Soumyajit Nandi",
  "Shivam Sunil Kalangan",
  "Yugal Manoj Sadhwani",
  "Chandan K T",
];

const girlsName = [
  "Keerthika Jain",
  "Anvita S Reddy",
  "Bhumi Sachdev",
  "Divyanteeka",
  "Priyanka Chauhan",
  "Sneha Chaurasia",
  "Saniya Singh",
  "Shivadharushni M",
  "Tanzila Tahreem",
  "Shivika Omprakash",
  "Annu",
  "Divyanshi Vinod Talreja",
  "Kanishka",
  "Saloni Kumari",
  "Sristy Anand",
  "Sejal Kumari",
  "Vijeta Narwal",
  "Ananya Chavan",
  "Ipshita Baral",
  "Kurapati Sree Varun Aahil",
  "Nivedita",
  "Rhythm Gulia",
  "Riya Kumari",
  "Tarmanjeet Kaur",
  "Varsha R",
  "Ananya Kolekar",
  "Deepanshi",
  "Gunjan Maheswari",
  "Nidhi Singh",
  "Priya",
  "Priyanka Potlia",
  "Tanya",
];

console.log(boysNames.length);
console.log(girlsName.length);
